### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Trobyss** [social-manager-tools/socialmanagertools-igbot#164]
Hi !

I just update win the latest version of you're project. I use docker on my raspberry:armv7. When I start docker machine, i have this error:

```
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/app/modules/common/utils.js:60:20)
    at self.callback (/app/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/app/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
2019-03-31T15:15:11: PM2 log: App [socialmanagertools-igbot:0] exited with code [1] via signal [SIGINT]
```
Any idea ? 
(ps: my config.js is correct)
Trob'

**Comment by ptkdev** [comment]
Docker has problem with contact server:
`https://api.socialmanager.tools/v2/bot/instagram/version/`
you can download with curl this link? Imho is temporarily problem. Retry and work.

**Comment by Trobyss** [comment]
What did you mean when you say "download with curl this link" ?  I have just this when i curl this link `{
"master":{ "version":"0.9.12" },
"beta":{ "version":"0.9.12" },
"nightly":{ "version":"0.10.0" }
}`

**Comment by ptkdev** [comment]
Ok docker read json correctly. If you retry run docker again, not work again?

**Comment by Trobyss** [comment]
curl isn't install so after an apt-get install, i have this : 
`<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
`

**Comment by ptkdev** [comment]
Ok, thanks this is very good bug report for me. I try resolve this tonight. I write you when fix server redirect.

**Comment by Trobyss** [comment]
Okay :) thanks a lot !

**Comment by Trobyss** [comment]
Did you do something ? Docker run without error now

**Comment by ptkdev** [comment]
Without curl install you give ever error?
If you install curl error disappear?

In next release I add curl dependence in docker if you confirm me this ❤️

**Comment by Trobyss** [comment]
Yes i confirm :D

**Comment by ptkdev** [comment]
I test this fix and next hours try release new version of docker hub container. Thanks bro.

**Comment by ptkdev** [comment]
Fixed in `v0.9.13`

**Comment by asherism** [comment]
I'm still having this issue. 

`curl https://api.socialmanager.tools/v2/bot/instagram/version`

returns the 301 error

**Comment by ptkdev** [comment]
@asherism on docker? Latest release v0.9.14 fix this issue, drop and re-pull new container

**Comment by ptkdev** [comment]
@Trobyss you can test latest container with native curl installation? Thanks (you are my docker beta tester 😂)

**Comment by ptkdev** [comment]
@asherism install `ca-certificates`, i start rebuild the dockers containers with this fix. Wait 2-3h and retry

**Comment by asherism** [comment]
is there a particular certificate that i need to create?

running this on a raspberry pi 3

**Comment by ptkdev** [comment]
I started rebuilding the container dockers with the fix but dockerhub is slow (they will be distributed tomorrow). If you want a manual solution:
1. `docker exec -it <container name> /bin/bash`
2. `apt-get install ca-certificates`
3. `exit`
4. Restart the container

**Comment by asherism** [comment]
back up and running, thank you 🙏
