### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by winsoncky** [social-manager-tools/socialmanagertools-igbot#167]
Hi,

I was using the previous socialmanagertools for IG and everything works fine before, but seems I found it does not work anymore this few months and I check with Github find this socialmanagertools-igbot. I had install it and correct those information in config.js, seems it cannot run and came out the error "TypeError: Cannot read property 'forEach' of undefined" with the following:

at new Log (/app/modules/logger/log.js:11:27) 
at new Utils (/app/modules/common/utils.js:21:14)
at module.exports (/app/modules/common/utils.js:359:9)
at module.exports.start (/app/lib.js:59:48)
at Object.<anonymous> (/app/bot.js:30:5) 
at Module._compile (module.js:652:30) 
at Object.Module._extensions..js (module.js:663:10) 
at Module.load (module.js:565:32) 
at tryModuleLoad (module.js:505:12) 
at Function.Module._load (module.js:497:3)

I was wondering if there is any I had mistakenly configured? May I have you guild for the configuration?

Thanks,

Winson

**Comment by ptkdev** [comment]
Hi!
Please config and command you use for run app. @winsoncky

**Comment by ptkdev** [comment]
Fixed in **v0.9.17**

**Comment by soulduse** [comment]
Same to me.
I changed version v0.9.17 
I still get error. @ptkdev :( pleas help me.

**Comment by soulduse** [comment]
This is my config

```json
module.exports = {
	// Developer Configs
	"system": {
		"config_version": "1.0.0",   // version of this file, version increase if change values from previously config
		"language": "en",            // available: en = English / it = Italian
		"raspberry": "disabled",     // if you use raspbian this fix automatically common issues
		"ui": "disabled",            // enabled/disabled only if you work at social-manager-tools GUI
		"terminal_colors": "enabled" // enabled/disabled if you want colors in windows power shell/cmd, mac console or linux terminal
	},

	// Instagram Account
	"account": {
		"username": "name",   // instagram nickname
		"password": "password", // instagram password
		"pin_method": "auto"    // 2FA: method for receive pin (auto: first authenticator if is enabled and after sms)
	},

	// Set Bot Mode, available:
	// likemode_classic            - select random hashtag from config list and like 1 random photo (of last 20)
	// likemode_realistic          - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min
	// likemode_realistic_location - select random gps-location from config list, like fast 10-12 photo and sleep 15-20min
	// likemode_realistic_timeline - like fast 10-12 photo from your timeline and sleep 15-20min
	// likemode_superlike          - select random hashtag from config list and like 3 random photo of same user
	// likemode_superlike_location - select random gps-location from config list and like 3 random photo of same user
	// likemode_competitor_users   - select account, select random followers, like 10-12 photo and sleep 15-20min
	// commentmode_classic         - leave a comment under the photo via hashtag
	// commentmode_location        - leave a comment under the photo via gps-location
	// fdfmode_classic             - follow 30 users, and defollow the first followed at 31 follow, follow 1 (in loop)
	// fdfmode_classic_location    - select random gps-location, follow 30 users, and defollow the first followed at 31 follow, follow 1 (in loop)
	//
	// Modes details: http://docs.socialmanager.tools/igbot/installation/modes
	// Multi account: http://docs.socialmanager.tools/igbot/installation/multiaccount
	"bot_mode": "likemode_realistic", // this is NOT array. 1 mode is allowed

	// Edit options of current bot_mode you use.
	"bot_mode_options": {
		"likemode_realistic": {
			"hashtags": [
				"해루질",
				"갯벌체험",
				"맛조개잡이",
				"맛조개",
				"몽산포해수욕장",
				"태안여행",
				"서해바다",
				"갯벌",
				"몽산포해수욕장",
				"만리포해수욕장",
				"꽃지해수욕장",
				"청포대해수욕장",
				"몽산포해수욕장",
				"밧개해수욕장",
				"삼봉해수욕장",
				"마검포해수욕장",
				"바람아래해수욕장",
				"풍하해루질",
				"선상낚시",
				"문어낚시"
			], // recommended more than 20
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled", // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_realistic.json" // json databases with modes info for better report
			},
		},
		"likemode_realistic_location": {
			"instagram_location": ["213050058", "31499759", "675369430"], // recommended more than 20
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled", // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_realistic_location.json" // json databases with modes info for better report
			},
		},
		"likemode_realistic_myfeed": {
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled", // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_realistic_myfeed.json" // json databases with modes info for better report
			},
		},
		"likemode_classic": {
			"hashtags": ["rome", "italy", "muraleshunter"], // recommended more than 20
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled", // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_classic.json" // json databases with modes info for better report
			},
		},
		"likemode_classic_location": {
			"instagram_location": ["213050058", "31499759", "675369430"], // recommended more than 20
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled", // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_classic_location.json" // json databases with modes info for better report
			},
		},
		"likemode_superlike": {
			"hashtags": ["rome", "italy", "muraleshunter"], // recommended more than 20
			"superlike_n": "3",        // number of likes for user (max 12)
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled", // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_superlike.json" // json databases with modes info for better report
			},
		},
		"likemode_superlike_location": {
			"instagram_location": ["213050058", "31499759", "675369430"], // recommended more than 20
			"superlike_n": "3",        // number of likes for user (max 12)
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled", // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_superlike_location.json" // json databases with modes info for better report
			},
		},
		"commentmode_realistic": {
			"hashtags": [
				"해루질",
				"갯벌체험",
				"맛조개잡이",
				"조개잡이",
				"풍하해루질"
			], // recommended more than 20
			"comments_list": ["해루질 앱도 있어요 :)", "해루질 하러 가고 싶네요"], // recommended more than 10 (emoij supported)
			"comments_min": "10",      // min comments daily.
			"comments_max": "20",      // max comments daily. In 2018 limit instagram is 500/day
			"sleep_night": "disabled",  // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/commentmode_realistic.json" // json databases with modes info for better report
			},
		},
		"commentmode_realistic_location": {
			"instagram_location": ["213050058", "31499759", "675369430"], // recommended more than 20
			"comments_list": ["comment1", "comment2", "comment3"], // recommended more than 10
			"comments_min": "300",      // min comments daily.
			"comments_max": "400",      // max comments daily. In 2018 limit instagram is 500/day
			"sleep_night": "disabled",  // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/commentmode_realistic_location.json" // json databases with modes info for better report
			},
		},
		"fdfmode_realistic": {
			"hashtags": ["rome", "italy", "muraleshunter"], // recommended more than 20
			"followday": "300",   // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
			"followrotate": "30", // follow 30 users, and defollow the first followed at 31 follow (in loop). If is 0 defollow all followed users previously by bot
			"userwhitelist": ["user1", "user2", "user3"], // don't defollow this users
			"sleep_night": "disabled",  // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/fdfmode_classic.json" // json databases with modes info for better report
			},
		},
		"fdfmode_realistic_location": {
			"instagram_location": ["213050058", "31499759", "675369430"], // recommended more than 20
			"followday": "300",   // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
			"followrotate": "30", // follow 30 users, and defollow the first followed at 31 follow (in loop). If is 0 defollow all followed users previously by bot
			"userwhitelist": ["user1", "user2", "user3"], // don't defollow this users
			"sleep_night": "disabled",  // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/fdfmode_classic.json" // json databases with modes info for better report
			},
		},
		"likemode_competitor_users": {
			"account": "imvely_jihyun", // instagram nickname
			"likeday_min": "800",      // min like daily.
			"likeday_max": "900",      // max like daily. In 2018 limit instagram is 1000/day
			"sleep_night": "disabled",  // if you need stop bot in night
			"sleep_end": "7:00",        // sleep from 00:00 to 7:00 am
			"database": {
				"default": "./databases/likemode_competitor_users.json" // json databases with modes info for better report
			},
		},
	},

	// Force overwrite css selectors if not work, example: {"click_heart":"button#heart"}
	// Syntax is apiName_functionName_selectorName, example: write::comment() => {"write_comment_textarea":"article > textarea.comment"}
	"selectors": {},

	// Puppeteer Configs
	"puppeteer": {
		"chrome_headless": "disabled", // hide google chrome window
		"chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1024x768"], // google chrome args
		"chrome_useragent": "", // overwrite chrome user agent
		"chrome_executable_path": "" /* If you want run installed chrome browser, not from npm module
									  *  example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
									  *  example for Linux:  /usr/bin/chromium
									  */
	},

	// Proxy
	"proxy": {
		"server": "",
		"port": "",
	},

	// LOGS
	"log": {
		"path": {
			"pin": "./configs/loginpin.txt",
			"debug_log": "./logs/debug.log",
			"error_log": "./logs/errors.log",
			"screenshots": "./logs/screenshots/",
		},
		"screenshot": "disabled",  // enabled/disabled screenshot in logs/screenshots folder
		"debug": "enabled",        // enabled/disabled all logs with tag debug
		"info": "enabled",         // enabled/disabled all logs with tag info
		"warning": "enabled",      // enabled/disabled all logs with tag warning
		"errors": "enabled",       // enabled/disabled all logs with tag errors
	}
};
```

**Comment by ptkdev** [comment]
@soulduse hi! You use v0.10 config on v0.9.18 release. 

Get [v0.9.X config](https://github.com/social-manager-tools/socialmanagertools-igbot/blob/master/configs/config.js.tpl)

**Comment by soulduse** [comment]
@ptkdev Works thank a lot! 👍
